# Generated by Django 4.2.6 on 2023-10-19 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_advocate_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='advocate',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='advocate',
            name='profile_pic',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='advocate',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='advocate',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
